export type Language = 'fr' | 'ar' | 'es' | 'ru' | 'zh';

export const TRANSLATIONS = {
    fr: {
        welcome: "Bienvenue chez Vendôme",
        welcomeBack: "Bienvenue, ",
        subtitle: "Beauté . Spa",
        tagline: "Où l'élégance rencontre la tranquillité",
        signIn: "Se connecter",
        signUp: "S'inscrire",
        email: "Adresse Email",
        password: "Mot de passe",
        forgot: "Mot de passe oublié ?",
        noAccount: "Pas de compte ?",
        haveAccount: "Déjà un compte ?",
        createAccount: "Créer un compte",
        dashboard: "Tableau de bord",
        specialists: "Spécialistes",
        history: "Historique",
        points: "Points de fidélité",
        nextReward: "Prochaine récompense",
        recommendations: "Pour votre prochaine venue",
        recentVisits: "Visites récentes",
        addComment: "Ajouter un commentaire",
        bookNow: "Réserver",
        services: "Nos Services d'Exception",
        luxuryAmenities: "Aménagements de Luxe",
        signOut: "Se déconnecter",
        ptsAway: "pts restants",
        maintenant: "Maintenant",
        products: "Produits",
        clients: "Clients",
        cart: "Mon Panier",
        referrals: "Parrainages",
        getRefCode: "Vous avez un code ?",
        apply: "Appliquer",
        pendingServices: "Services en attente",
        total: "Total",
        continueShopping: "Continuer mes achats",
        pay: "Payer",
        noPending: "Aucun service en attente.",
        noClients: "Aucun client trouvé.",
        evaluateSpecialist: "Évaluer le spécialiste",
        saveEvaluation: "Enregistrer l'évaluation",
        cancel: "Annuler",
        shareExperience: "Partagez votre expérience...",
        availableTime: "Heures disponibles",
        selectSpecialist: "Choisir un spécialiste",
        confirmReservation: "Confirmer la réservation",
        confirmBooking: "Confirmer la réservation",
        selectDate: "Choisir une date",
        liveLounge: "Espace Live",
        currentQueue: "File d'attente",
        estWait: "Attente estimée",
        joinConversation: "Rejoindre la conversation",
        post: "Publier",
        boutique: "Boutique",
        shareThought: "Partagez une pensée ou une demande...",
        addedToCart: "Ajouté au panier",
        tip: "Pourboire",
        tipAmount: "Montant du pourboire (DT) :",
        tipSent: "Pourboire envoyé !",
        with: "avec",
        clientsList: "Liste des clients",
        evalSaved: "Évaluation enregistrée !",
        evalFailed: "Échec de l'évaluation",
        resConfirmed: "Réservation confirmée !",
        bookingFailed: "Échec de la réservation",
        cancelRes: "Annuler cette réservation ?",
        resCancelled: "Réservation annulée !",
        failCancel: "Échec de l'annulation",
        addToCart: "Ajouter au panier",
        howWasSession: "Comment s'est passée votre séance avec {name} ?",
        dismiss: "Ignorer",
        thankYouReview: "Merci pour votre avis de {rating} étoiles !",
        shareFeedback: "Partager mon avis",
        exclusiveRitual: "Rituel Exclusif",
        recentReviews: "Avis Récents",
        whatToExpect: "Ce qui vous attend :",
        immediateRejuvenation: "Rajeunissement Immédiat",
        premiumOrganic: "Produits Bio Premium",
        personalizedConsultation: "Consultation Personnalisée",
        backToDashboard: "Retour au Tableau de bord",
        bestSpecialist2025: "MEILLEUR SPÉCIALISTE 2025",
        evaluationLabel: "ÉVALUATION",
        satisfiedClients: "CLIENTS SATISFAITS",
        expertiseLevels: "Niveaux d'Expertise",
        technique: "Technique",
        hospitality: "Hospitalité",
        precision: "Précision",
        vendomeExclusivity: "EXCLUSIVITÉ VENDÔME",
        journeyOfExcellence: "Parcours d'Excellence",
        staffBioTemplate: "{name} est l'une des figures de proue de notre établissement. Diplômée des plus prestigieuses académies internationales, elle a consacré sa carrière à la maîtrise des rituels de soin les plus sophistiqués. Ses protocoles personnalisés en {specialty} sont reconnus pour leurs résultats immédiats et leur dimension profondément relaxante. Chaque geste est une signature, chaque séance est une renaissance.",
        cleanEquipment: "Matériel Propre",
        immediateEffect: "Effet Immédiat",
        absoluteLuxury: "Luxe Absolu",
        electronicGuestbook: "Livre d'Or Électronique",
        shareValuableReview: "Partagez votre précieux avis sur la prestation de {name}",
        whatToSayTo: "Que souhaitez-vous dire à {name} ?...",
        publicPrivacyMsg: "Votre avis sera visible publiquement par la communauté Elite.",
        changePhoto: "Changer la photo",
        uploadPhoto: "Télécharger une photo",
        editUser: "Modifier l'utilisateur",
        editService: "Modifier le service",
        uploadImage: "Télécharger une image",
        changeImage: "Changer l'image",
        userUpdated: "Utilisateur mis à jour !",
        leaveEmpty: "Laisser vide pour ne pas changer",
        manageServices: "Gérer les services",
        save: "Enregistrer",
        edit: "Modifier",
        delete: "Supprimer",
        confirmDeleteUser: "Voulez-vous vraiment supprimer cet utilisateur ?",
        confirmDeleteService: "Voulez-vous vraiment supprimer ce service ?",
        name: "Nom",
        description: "Description",
        price: "Prix",
        duration: "Durée",
        active: "Actif",
        disabled: "Désactivé",
        enable: "Activer",
        disable: "Désactiver",
        remove: "Supprimer",
        publishMyReview: "PUBLIER MON AVIS",
        pleaseRate: "Veuillez attribuer une note étoilée.",
        sublimePublished: "Sublime ! Votre avis pour {name} a été publié.",
        weeklyTestimonials: "Témoignages de la semaine",
        hoursAgo: "Il y a {count} heures",
        testimonialStaffOne: "Un moment suspendu hors du temps. {name} a des mains de fée et une écoute rare. Je reviendrai sans hésiter pour son expertise en {specialty}.",
        eliteAccessOnly: "Accès Élite Uniquement",
        joinCommunity: "Rejoignez notre communauté exclusive",
        continueGoogle: "Continuer avec Google",
        or: "OU",
        fullName: "Nom Complet",
        accountCreated: "Compte créé ! Veuillez vous connecter.",
        errorOccurred: "Une erreur est survenue. Veuillez réessayer.",
        failedGoogleSync: "Échec de la connexion avec Google.",
        platformStatistics: "Statistiques de la plateforme",
        totalClients: "Total Clients",
        totalServices: "Total Services",
        totalSpecialists: "Total Spécialistes",
        activeFeedback: "Commentaires Actifs",
        availableServices: "Services Disponibles",
        // active: "Actif", // Already exists above
        // disabled: "Désactivé", // Already exists above
        // enable: "Activer", // Already exists above
        // disable: "Désactiver", // Already exists above
        // confirmDeleteService: "Êtes-vous sûr de vouloir supprimer ce service?", // Already exists above
        // manageServices: "Gérer les Services", // Already exists above
        addService: "Ajouter un Service",
        // remove: "Supprimer", // Already exists above
        manageClients: "Gérer les Clients",
        // confirmDeleteUser: "Êtes-vous sûr de vouloir supprimer cet utilisateur?", // Already exists above
        // delete: "Supprimer", // Already exists above
        // name: "Nom", // Already exists above
        // description: "Description", // Already exists above
        // price: "Prix", // Already exists above
        image: "URL de l'image",
        feedback: "Avis & Retour",
        addProduct: "Ajouter un Produit",
        editProduct: "Modifier le Produit",
        confirmDelete: "Supprimer cet élément ?",
        productAdded: "Produit ajouté !",
        productUpdated: "Produit mis à jour !",
        memberStatus: "Statut Membre",
        goldMember: "Membre Gold",
        normalMember: "Normal",
        success: "Succès",
        error: "Erreur",
        ficheClient: "Fiche Client",
        hairColorPref: "Couleur cheveux préférée",
        coffeePref: "Café préféré",
        employeePref: "Employé préféré",
        favouriteService: "Service préféré",
        allergies: "Allergies / Particularités",
        lastVisitNotes: "Notes de la dernière visite",
        addClient: "Ajouter Client",
        add: "Ajouter",
        phone: "Téléphone",
        birthday: "Date de naissance"
    },
    ar: {
        welcome: "مرحباً بكم في فاندوم",
        welcomeBack: "مرحباً، ",
        subtitle: "تجميل . سبا",
        tagline: "حيث تلتقي الأناقة بالهدوء",
        signIn: "تسجيل الدخول",
        signUp: "إنشاء حساب",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        forgot: "نسيت كلمة المرور؟",
        noAccount: "ليس لديك حساب؟",
        haveAccount: "لديك حساب بالفعل؟",
        createAccount: "أنشئ حساباً",
        dashboard: "لوحة التحكم",
        specialists: "المتخصصون",
        history: "السجل",
        points: "نقاط الولاء",
        nextReward: "المكافأة التالية",
        recommendations: "مقترحات لزيارتك القادمة",
        recentVisits: "الزيارات الأخيرة",
        addComment: "إضافة تعليق",
        bookNow: "احجز الآن",
        services: "خدماتنا المتميزة",
        luxuryAmenities: "مرافق فاخرة",
        signOut: "تسجيل الخروج",
        ptsAway: "نقطة متبقية",
        maintenant: "الآن",
        products: "المنتجات",
        clients: "العملاء",
        cart: "سلة المشتريات",
        referrals: "الإحالات",
        getRefCode: "هل لديك رمز إحالة؟",
        apply: "تطبيق",
        pendingServices: "خدمات قيد الانتظار",
        total: "المجموع",
        continueShopping: "مواصلة التسوق",
        pay: "دفع",
        noPending: "لا توجد خدمات معلقة.",
        noClients: "لم يتم العثور على عملاء.",
        evaluateSpecialist: "تقييم المتخصص",
        saveEvaluation: "حفظ التقييم",
        cancel: "إلغاء",
        shareExperience: "شارك تجربتك...",
        availableTime: "الأوقات المتاحة",
        selectSpecialist: "اختر متخصصاً",
        confirmReservation: "تأكيد الحجز",
        confirmBooking: "تأكيد الحجز",
        selectDate: "اختر التاريخ",
        liveLounge: "الغرفة المباشرة",
        currentQueue: "قائمة الانتظار الحالية",
        estWait: "الانتظار المتوقع",
        joinConversation: "انضم إلى المحادثة",
        post: "نشر",
        boutique: "المتجر",
        shareThought: "شارك فكرة أو طلباً...",
        addedToCart: "تمت الإضافة إلى السلة",
        tip: "إكرامية",
        tipAmount: "مبلغ الإكرامية (DT):",
        tipSent: "تم إرسال الإكرامية!",
        with: "مع",
        clientsList: "قائمة العملاء",
        evalSaved: "تم حفظ التقييم!",
        evalFailed: "فشل حفظ التقييم",
        resConfirmed: "تم تأكيد الحجز!",
        bookingFailed: "فشل الحجز",
        cancelRes: "هل تريد إلغاء هذا الحجز؟",
        resCancelled: "تم إلغاء الحجز بنجاح!",
        failCancel: "فشل إلغاء الحجز",
        addToCart: "إضافة إلى السلة",
        howWasSession: "كيف كانت جلستك مع {name}؟",
        dismiss: "تجاهل",
        thankYouReview: "شكراً لتقييمك بـ {rating} نجوم!",
        shareFeedback: "مشاركة التقييم",
        exclusiveRitual: "طقوس حصرية",
        recentReviews: "آراء حديثة",
        whatToExpect: "ماذا تتوقع:",
        immediateRejuvenation: "تجديد فوري",
        premiumOrganic: "منتجات عضوية فاخرة",
        personalizedConsultation: "استشارة شخصية",
        backToDashboard: "العودة إلى لوحة التحكم",
        bestSpecialist2025: "أفضل متخصص 2025",
        evaluationLabel: "تقييم",
        satisfiedClients: "عملاء راضون",
        expertiseLevels: "مستويات الخبرة",
        technique: "التقنية",
        hospitality: "الضيافة",
        precision: "الدقة",
        vendomeExclusivity: "حصري لفاندوم",
        journeyOfExcellence: "رحلة التميز",
        staffBioTemplate: "{name} هي واحدة من أبرز الشخصيات في مؤسستنا. تخرجت من أرقى الأكاديميات الدولية، وكرست حياتها المهنية لإتقان أكثر طقوس العناية تطوراً. بروتوكولاتها المخصصة في {specialty} معروفة بنتائجها الفورية وأبعادها المريحة للغاية. كل لفتة هي توقيع، وكل جلسة هي ولادة جديدة.",
        cleanEquipment: "معدات نظيفة",
        immediateEffect: "تأثير فوري",
        absoluteLuxury: "فخامة مطلقة",
        electronicGuestbook: "سجل الزوار الإلكتروني",
        shareValuableReview: "شاركنا رأيك القيم في أداء {name}",
        whatToSayTo: "ماذا تود أن تقول لـ {name}؟...",
        publicPrivacyMsg: "سيكون رأيك مرئياً للجميع في مجتمع إيليت.",
        publishMyReview: "نشر التقييم",
        pleaseRate: "يرجى تقديم تقييم بالنجوم.",
        sublimePublished: "رائع! تم نشر تقييمك لـ {name}.",
        weeklyTestimonials: "شهادات الأسبوع",
        hoursAgo: "منذ {count} ساعة",
        testimonialStaffOne: "لحظة معلقة خارج الزمن. {name} لديها يدان ساحرتان وإنصات نادر. سأعود بالتأكيد لتجربة خبرتها في {specialty}.",
        eliteAccessOnly: "دخول للنخبة فقط",
        joinCommunity: "انضم إلى مجتمعنا الحصري",
        continueGoogle: "المتابعة باستخدام جوجل",
        or: "أو",
        fullName: "الاسم الكامل",
        accountCreated: "تم إنشاء الحساب! يرجى تسجيل الدخول.",
        errorOccurred: "حدث خطأ. يرجى المحاولة مرة أخرى.",
        editUser: "تعديل المستخدم",
        editService: "تعديل الخدمة",
        uploadImage: "تحميل صورة",
        changeImage: "تغيير الصورة",
        userUpdated: "تم تحديث المستخدم!",
        leaveEmpty: "اتركه فارغاً لعدم التغيير",
        manageServices: "إدارة الخدمات",
        save: "حفظ",
        edit: "تعديل",
        delete: "حذف",
        confirmDeleteUser: "هل أنت متأكد من حذف هذا المستخدم؟",
        confirmDeleteService: "هل أنت متأكد من حذف هذه الخدمة؟",
        name: "الاسم",
        description: "الوصف",
        price: "السعر",
        duration: "المدة",
        active: "نشط",
        disabled: "معطل",
        enable: "تفعيل",
        disable: "تعطيل",
        remove: "إزالة",
        failedGoogleSync: "فشل تسجيل الدخول باستخدام جوجل.",
        platformStatistics: "إحصائيات المنصة",
        totalClients: "إجمالي العملاء",
        totalServices: "إجمالي الخدمات",
        totalSpecialists: "إجمالي المتخصصين",
        activeFeedback: "التعليقات النشطة",
        availableServices: "الخدمات المتاحة",
        manageClients: "إدارة العملاء",
        addService: "إضافة خدمة",
        feedback: "الآراء والتعليقات",
        image: "رابط الصورة",
        addProduct: "إضافة منتج",
        editProduct: "تعديل المنتج",
        confirmDelete: "هل تريد حذف هذا العنصر؟",
        productAdded: "تم إضافة المنتج بنجاح!",
        productUpdated: "تم تحديث المنتج!",
        memberStatus: "حالة العضوية",
        goldMember: "عضو ذهبي",
        normalMember: "عادي",
        success: "نجاح",
        error: "خطأ"
    },
    es: {
        welcome: "Bienvenido a Vendôme",
        welcomeBack: "Bienvenido, ",
        subtitle: "Belleza . Spa",
        tagline: "Donde la elegancia se encuentra con la tranquilidad",
        signIn: "Iniciar sesión",
        signUp: "Registrarse",
        email: "Correo electrónico",
        password: "Contraseña",
        forgot: "¿Olvidaste tu contraseña?",
        noAccount: "¿No tienes cuenta?",
        haveAccount: "¿Ya tienes cuenta?",
        createAccount: "Crear cuenta",
        dashboard: "Panel de control",
        specialists: "Especialistas",
        history: "Historial",
        points: "Puntos de fidelidad",
        nextReward: "Próxima recompensa",
        recommendations: "Para su próxima visita",
        recentVisits: "Visitas recientes",
        addComment: "Añadir comentario",
        bookNow: "Reservar ahora",
        services: "Nuestros Servicios Excepcionales",
        luxuryAmenities: "Instalaciones de Lujo",
        signOut: "Cerrar sesión",
        ptsAway: "pts restantes",
        maintenant: "Ahora",
        products: "Productos",
        clients: "Clientes",
        cart: "Mi Carrito",
        referrals: "Referidos",
        getRefCode: "¿Tienes un código?",
        apply: "Aplicar",
        pendingServices: "Servicios pendientes",
        total: "Total",
        continueShopping: "Continuar comprando",
        pay: "Pagar",
        noPending: "No hay servicios pendientes.",
        noClients: "No se encontraron clientes.",
        evaluateSpecialist: "Evaluar especialista",
        saveEvaluation: "Guardar evaluación",
        cancel: "Cancelar",
        shareExperience: "Comparte tu experiencia...",
        availableTime: "Horarios disponibles",
        selectSpecialist: "Seleccionar especialista",
        confirmReservation: "Confirmar reserva",
        confirmBooking: "Confirmar reserva",
        selectDate: "Seleccionar fecha",
        liveLounge: "Sala en vivo",
        currentQueue: "Cola actual",
        estWait: "Espera estimada",
        joinConversation: "Unirse a la conversación",
        post: "Publicar",
        boutique: "Tienda",
        shareThought: "Comparte un pensamiento o solicitud...",
        addedToCart: "Agregado al carrito",
        tip: "Propina",
        tipAmount: "Monto de la propina (DT):",
        tipSent: "¡Propina enviada!",
        with: "con",
        clientsList: "Lista de clientes",
        evalSaved: "¡Evaluación guardada!",
        evalFailed: "Error al guardar la evaluación",
        resConfirmed: "¡Reserva confirmada!",
        bookingFailed: "Error en la reserva",
        cancelRes: "¿Cancelar esta reserva?",
        resCancelled: "¡Reserva cancelada con éxito!",
        failCancel: "Error al cancelar la reserva",
        addToCart: "Añadir al carrito",
        howWasSession: "¿Cómo fue tu sesión con {name}?",
        dismiss: "Descartar",
        thankYouReview: "¡Gracias por tu reseña de {rating} estrellas!",
        shareFeedback: "Compartir opinión",
        exclusiveRitual: "Ritual Exclusivo",
        recentReviews: "Reseñas Recientes",
        whatToExpect: "Qué esperar:",
        immediateRejuvenation: "Rejuvenecimiento Inmediato",
        premiumOrganic: "Productos Orgánicos Premium",
        personalizedConsultation: "Consulta Personalizada",
        backToDashboard: "Volver al Panel",
        bestSpecialist2025: "MEJOR ESPECIALISTA 2025",
        evaluationLabel: "EVALUACIÓN",
        satisfiedClients: "CLIENTES SATISFECHOS",
        expertiseLevels: "Niveles de Experiencia",
        technique: "Técnica",
        hospitality: "Hospitalidad",
        precision: "Precisión",
        vendomeExclusivity: "EXCLUSIVIDAD VENDÔME",
        journeyOfExcellence: "Trayectoria de Excelencia",
        staffBioTemplate: "{name} es una de las figuras destacadas de nuestro establecimiento. Graduada en las academias internacionales más prestigiosas, ha dedicado su carrera al dominio de los rituales de cuidado más sofisticados. Sus protocolos personalizados en {specialty} son reconocidos por sus resultados inmediatos y su dimensión profundamente relajante. Cada gesto es una firma, cada sesión es un renacimiento.",
        cleanEquipment: "Equipo Limpio",
        immediateEffect: "Efecto Inmediato",
        absoluteLuxury: "Lujo Absoluto",
        electronicGuestbook: "Libro de Visitas Electrónico",
        shareValuableReview: "Comparte tu valiosa opinión sobre el servicio de {name}",
        whatToSayTo: "¿Qué le gustaría decirle a {name}?... ",
        publicPrivacyMsg: "Tu opinión será visible públicamente para la comunidad Elite.",
        publishMyReview: "PUBLICAR MI OPINIÓN",
        pleaseRate: "Por favor, asigne una calificación de estrellas.",
        sublimePublished: "¡Sublime! Tu opinión para {name} ha sido publicada.",
        weeklyTestimonials: "Testimonios de la semana",
        hoursAgo: "Hace {count} horas",
        testimonialStaffOne: "Un momento suspendido fuera del tiempo. {name} tiene manos de hada y una escucha rara. Volveré sin duda por su experiencia en {specialty}.",
        eliteAccessOnly: "Solo Acceso Élite",
        joinCommunity: "Únete a nuestra comunidad exclusiva",
        continueGoogle: "Continuar con Google",
        or: "O",
        fullName: "Nombre Completo",
        accountCreated: "¡Cuenta creada! Por favor, inicia sesión.",
        errorOccurred: "Ocurrió un error. Por favor, inténtalo de nuevo.",
        editUser: "Editar usuario",
        editService: "Editar servicio",
        uploadImage: "Subir imagen",
        changeImage: "Cambiar imagen",
        userUpdated: "¡Usuario actualizado!",
        leaveEmpty: "Dejar vacío para no cambiar",
        manageServices: "Gestionar servicios",
        save: "Guardar",
        edit: "Editar",
        delete: "Eliminar",
        confirmDeleteUser: "¿Realmente desea eliminar este usuario?",
        confirmDeleteService: "¿Realmente desea eliminar este servicio?",
        name: "Nombre",
        description: "Descripción",
        price: "Precio",
        duration: "Duración",
        active: "Activo",
        disabled: "Deshabilitado",
        enable: "Habilitar",
        disable: "Deshabilitar",
        remove: "Eliminar",
        failedGoogleSync: "Error al iniciar sesión con Google.",
        platformStatistics: "Estadísticas de la plataforma",
        totalClients: "Total Clientes",
        totalServices: "Total Servicios",
        totalSpecialists: "Total Especialistas",
        activeFeedback: "Comentarios Activos",
        availableServices: "Servicios Disponibles",
        manageClients: "Gestionar Clientes",
        addService: "Añadir Servicio",
        feedback: "Opiniones y Comentarios",
        image: "URL de la imagen",
        addProduct: "Añadir un Producto",
        editProduct: "Editar Producto",
        confirmDelete: "¿Eliminar este elemento?",
        productAdded: "¡Producto añadido!",
        productUpdated: "¡Producto actualizado!",
        success: "Éxito",
        error: "Error"
    },
    ru: {
        welcome: "Добро пожаловать в Vendôme",
        welcomeBack: "Добро пожаловать, ",
        subtitle: "Красота . Спа",
        tagline: "Где элегантность встречается с умиротворением",
        signIn: "Войти",
        signUp: "Зарегистрироваться",
        email: "Электронная почта",
        password: "Пароль",
        forgot: "Забыли пароль?",
        noAccount: "Нет аккаунта?",
        haveAccount: "Уже есть аккаунт?",
        createAccount: "Создать аккаунт",
        dashboard: "Панель управления",
        specialists: "Специалисты",
        history: "История",
        points: "Бонусные баллы",
        nextReward: "Следующая награда",
        recommendations: "Рекомендации на следующий визит",
        recentVisits: "Последние визиты",
        addComment: "Добавить отзыв",
        bookNow: "Забронировать",
        services: "Наши исключительные услуги",
        luxuryAmenities: "Роскошные удобства",
        signOut: "Выйти",
        ptsAway: "баллов осталось",
        maintenant: "Сейчас",
        products: "Товары",
        clients: "Клиенты",
        cart: "Корзина",
        referrals: "Рефералы",
        getRefCode: "Есть код?",
        apply: "Применить",
        pendingServices: "Ожидающие услуги",
        total: "Итого",
        continueShopping: "Продолжить покупки",
        pay: "Оплатить",
        noPending: "Нет ожидающих услуг.",
        noClients: "Клиенты не найдены.",
        evaluateSpecialist: "Оценить специалиста",
        saveEvaluation: "Сохранить оценку",
        cancel: "Отмена",
        shareExperience: "Поделитесь своим опытом...",
        availableTime: "Доступное время",
        selectSpecialist: "Выбрать специалиста",
        confirmReservation: "Подтвердить бронирование",
        confirmBooking: "Подтвердить бронирование",
        selectDate: "Выбрать дату",
        liveLounge: "Прямой эфир",
        currentQueue: "Текущая очередь",
        estWait: "Ожидаемое время",
        joinConversation: "Присоединиться к беседе",
        post: "Опубликовать",
        boutique: "Бутик",
        shareThought: "Поделитесь мыслью или запросом...",
        addedToCart: "Добавлено в корзину",
        tip: "Чаевые",
        tipAmount: "Сумма чаевых (DT):",
        tipSent: "Чаевые отправлены!",
        with: "с",
        clientsList: "Список клиентов",
        evalSaved: "Оценка сохранена!",
        evalFailed: "Ошибка сохранения оценки",
        resConfirmed: "Бронирование подтверждено!",
        bookingFailed: "Ошибка бронирования",
        cancelRes: "Отменить это бронирование?",
        resCancelled: "Бронирование успешно отменено!",
        failCancel: "Ошибка отмены бронирования",
        addToCart: "Добавить в корзину",
        howWasSession: "Как прошел ваш сеанс с {name}?",
        dismiss: "Закрыть",
        thankYouReview: "Спасибо за ваш {rating}-звездочный отзыв!",
        shareFeedback: "Поделиться отзывом",
        exclusiveRitual: "Эксклюзивный Ритуал",
        recentReviews: "Последние Отзывы",
        whatToExpect: "Чего ожидать:",
        immediateRejuvenation: "Мгновенное Омоложение",
        premiumOrganic: "Премиальные Биопродукты",
        personalizedConsultation: "Индивидуальная Консультация",
        backToDashboard: "Вернуться в Панель",
        bestSpecialist2025: "ЛУЧШИЙ СПЕЦИАЛИСТ 2025",
        evaluationLabel: "ОЦЕНКА",
        satisfiedClients: "ДОВОЛЬНЫЕ КЛИЕНТЫ",
        expertiseLevels: "Уровни Мастерства",
        technique: "Техника",
        hospitality: "Гостеприимство",
        precision: "Точность",
        vendomeExclusivity: "ЭКСКЛЮЗИВ VENDÔME",
        journeyOfExcellence: "Путь Превосходства",
        staffBioTemplate: "{name} — одна из ведущих фигур нашего заведения. Выпускница самых престижных международных академий, она посвятила свою карьеру освоению самых изысканных ритуалов ухода. Ее персонализированные протоколы в области {specialty} известны своими мгновенными результатами и глубоким расслабляющим эффектом. Каждый жест — это подпись, каждый сеанс — возрождение.",
        cleanEquipment: "Чистое Оборудование",
        immediateEffect: "Мгновенный Эффект",
        absoluteLuxury: "Абсолютная Роскошь",
        electronicGuestbook: "Электронная Гостевая Книга",
        shareValuableReview: "Поделитесь своим ценным мнением о работе {name}",
        whatToSayTo: "Что вы хотите сказать {name}?... ",
        publicPrivacyMsg: "Ваш отзыв будет виден всему сообществу Elite.",
        errorOccurred: "Произошла ошибка. Пожалуйста, попробуйте еще раз.",
        editUser: "Редактировать пользователя",
        editService: "Редактировать услугу",
        uploadImage: "Загрузить изображение",
        changeImage: "Изменить изображение",
        image: "Ссылка на изображение",
        userUpdated: "Пользователь обновлен!",
        leaveEmpty: "Оставьте пустым, чтобы не менять",
        manageServices: "Управление услугами",
        save: "Сохранить",
        edit: "Изменить",
        delete: "Удалить",
        confirmDeleteUser: "Вы уверены, что хотите удалить этого пользователя?",
        confirmDeleteService: "Вы уверены, что хотите удалить эту услугу?",
        name: "Имя",
        description: "Описание",
        price: "Цена",
        duration: "Длительность",
        active: "Активно",
        disabled: "Отключено",
        enable: "Включить",
        disable: "Отключить",
        remove: "Удалить",
        failedGoogleSync: "Не удалось войти через Google.",
        platformStatistics: "Статистика платформы",
        totalClients: "Всего клиентов",
        totalServices: "Всего услуг",
        totalSpecialists: "Всего специалистов",
        activeFeedback: "Активные отзывы",
        availableServices: "Доступные услуги",
        addService: "Добавить услугу",
        manageClients: "Управление клиентами",
        feedback: "Оценки и отзывы",
        publishMyReview: "ОПУБЛИКОВАТЬ ОТЗЫВ",
        pleaseRate: "Пожалуйста, поставьте оценку.",
        sublimePublished: "Великолепно! Ваш отзыв о {name} опубликован.",
        weeklyTestimonials: "Отзывы недели",
        hoursAgo: "{count} часов назад",
        testimonialStaffOne: "Момент, застывший вне времени. У {name} волшебные руки и редкое умение слушать. Обязательно вернусь за ее экспертизой в {specialty}.",
        eliteAccessOnly: "Только для Элиты",
        joinCommunity: "Присоединяйтесь к нашему эксклюзивному сообществу",
        continueGoogle: "Войти через Google",
        or: "ИЛИ",
        fullName: "Полное Имя",
        accountCreated: "Аккаунт создан! Пожалуйста, войдите.",
        addProduct: "Добавить продукт",
        editProduct: "Редактировать продукт",
        confirmDelete: "Удалить этот элемент?",
        productAdded: "Продукт добавлен!",
        productUpdated: "Продукт обновлен!",
        success: "Успешно",
        error: "Ошибка"
    },
    zh: {
        welcome: "欢迎来到 Vendôme",
        welcomeBack: "欢迎，",
        subtitle: "美容 . 水疗",
        tagline: "优雅与宁静的邂逅之地",
        signIn: "登录",
        signUp: "注册",
        email: "电子邮件",
        password: "密码",
        forgot: "忘记密码？",
        noAccount: "没有账号？",
        haveAccount: "已有账号？",
        createAccount: "创建账号",
        dashboard: "仪表板",
        specialists: "专家",
        history: "历史记录",
        points: "忠诚度积分",
        nextReward: "下一阶段奖励",
        recommendations: "下次访问建议",
        recentVisits: "最近访问",
        addComment: "发表评论",
        bookNow: "现在预订",
        services: "我们的卓越服务",
        luxuryAmenities: "豪华设施",
        signOut: "登出",
        ptsAway: "积分还差",
        maintenant: "现在",
        products: "产品",
        clients: "客户",
        cart: "我的购物车",
        referrals: "推荐",
        getRefCode: "有代码吗？",
        apply: "应用",
        pendingServices: "待定服务",
        total: "总计",
        continueShopping: "继续购物",
        pay: "支付",
        noPending: "没有待定服务。",
        noClients: "尚未发现客户。",
        evaluateSpecialist: "评价专家",
        saveEvaluation: "保存评价",
        cancel: "取消",
        shareExperience: "分享您的体验...",
        availableTime: "可用时间",
        selectSpecialist: "选择专家",
        confirmReservation: "确认预约",
        confirmBooking: "确认预约",
        selectDate: "选择日期",
        liveLounge: "直播间",
        currentQueue: "当前队列",
        estWait: "预计等待",
        joinConversation: "加入对话",
        post: "发布",
        boutique: "精品店",
        shareThought: "分享想法或请求...",
        addedToCart: "已添加到购物车",
        tip: "小费",
        tipAmount: "小费金额 (DT):",
        tipSent: "小费已发送！",
        with: "与",
        clientsList: "客户列表",
        evalSaved: "评价已保存！",
        evalFailed: "评价保存失败",
        resConfirmed: "预约已确认！",
        bookingFailed: "预约失败",
        cancelRes: "取消此预约？",
        resCancelled: "预约已成功取消！",
        failCancel: "取消预约失败",
        addToCart: "加入购物车",
        howWasSession: "与 {name} 的服务体验如何？",
        dismiss: "忽略",
        thankYouReview: "感谢您的 {rating} 星评价！",
        shareFeedback: "分享反馈",
        exclusiveRitual: "专属仪式",
        recentReviews: "最新评价",
        whatToExpect: "服务期待：",
        immediateRejuvenation: "即时焕活",
        premiumOrganic: "优质有机产品",
        personalizedConsultation: "个性化咨询",
        backToDashboard: "回到仪表板",
        bestSpecialist2025: "2025 年度最佳专家",
        evaluationLabel: "评分",
        satisfiedClients: "满意客户",
        expertiseLevels: "专业水平",
        technique: "技术",
        hospitality: "款待",
        precision: "精准度",
        vendomeExclusivity: "Vendôme 独家专供",
        journeyOfExcellence: "卓越历程",
        staffBioTemplate: "{name} 是我们机构的佼佼者之一。她毕业于最负盛名的国际学院，致力于掌握最精致的护理仪式。她在 {specialty} 领域的个性化方案以即时效果和深层放松而闻名。每一个动作都是一份承诺，每一次服务都是一次重生。",
        cleanEquipment: "清洁设备",
        immediateEffect: "即时见效",
        absoluteLuxury: "绝对奢华",
        electronicGuestbook: "电子留言簿",
        shareValuableReview: "分享您对 {name} 服务的宝贵意见",
        whatToSayTo: "想对 {name} 说点什么？...",
        publicPrivacyMsg: "您的评价将对 Elite 社区公开可见。",
        publishMyReview: "发布我的评价",
        pleaseRate: "请给出星级评分。",
        sublimePublished: "太棒了！您对 {name} 的评价已发布。",
        weeklyTestimonials: "本周推荐",
        hoursAgo: "{count} 小时前",
        testimonialStaffOne: "一段超脱时间的宁静时光。{name} 有着神奇的双手和难得的倾听能力。我一定会为了她在 {specialty} 领域的专业能力再次光顾。",
        eliteAccessOnly: "仅限精英访问",
        joinCommunity: "加入我们的独家社区",
        continueGoogle: "使用 Google 继续",
        or: "或",
        fullName: "全名",
        accountCreated: "账号已创建！请登录。",
        errorOccurred: "发生错误。请重试。",
        editUser: "编辑用户",
        editService: "编辑服务",
        uploadImage: "上传图片",
        changeImage: "更改图片",
        userUpdated: "用户已更新！",
        leaveEmpty: "留空则不更改",
        manageServices: "管理服务",
        save: "保存",
        edit: "编辑",
        delete: "删除",
        confirmDeleteUser: "您确定要删除此用户吗？",
        confirmDeleteService: "您确定要删除此服务吗？",
        name: "名称",
        description: "描述",
        price: "价格",
        duration: "时长",
        active: "启用",
        disabled: "已禁用",
        enable: "启用",
        disable: "禁用",
        remove: "删除",
        image: "图片",
        failedGoogleSync: "无法通过 Google 登录。",
        platformStatistics: "平台统计",
        totalClients: "客户总数",
        totalServices: "服务总数",
        totalSpecialists: "专家总数",
        activeFeedback: "活跃反馈",
        availableServices: "可用服务",
        addService: "添加服务",
        manageClients: "管理客户",
        feedback: "反馈与评价",
        addProduct: "添加产品",
        editProduct: "编辑产品",
        confirmDelete: "删除此项？",
        productAdded: "产品已添加！",
        productUpdated: "产品已更新！",
        success: "成功",
        error: "错误"
    }
};

export interface Prestataire {
    id: string;
    name: string;
    role: string;
    image: string;
    rating: number;
    specialty: string;
}

export interface Service {
    id: string;
    name: string;
    description: string;
    price: string;
    image: string;
    duration: string;
}

export const SERVICES: Service[] = [
    {
        id: 's1',
        name: 'Massage Royal Vendôme',
        description: 'Une expérience de détente ultime utilisant des huiles essentielles rares et des pierres chaudes volcaniques.',
        price: '180€',
        image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80',
        duration: '90 min'
    },
    {
        id: 's2',
        name: 'Soin Visage Or Pur',
        description: 'Traitement anti-âge d\'exception aux particules d\'or 24 carats pour un éclat incomparable.',
        price: '250€',
        image: 'https://images.pexels.com/photos/3985338/pexels-photo-3985338.jpeg?auto=compress&cs=tinysrgb&w=800',
        duration: '75 min'
    },
    {
        id: 's3',
        name: 'Hammam Privé Signature',
        description: 'Rituel de purification traditionnel dans un cadre luxueux avec gommage au savon noir et enveloppement au rhassoul.',
        price: '120€',
        image: 'https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=800&q=80',
        duration: '60 min'
    },
    {
        id: 's4',
        name: 'Manucure Diamant',
        description: 'Soin complet des mains et des ongles avec finition joaillerie et modelage relaxant.',
        price: '95€',
        image: 'https://images.pexels.com/photos/3997391/pexels-photo-3997391.jpeg?auto=compress&cs=tinysrgb&w=800',
        duration: '45 min'
    }
];

export const PRESTATAIRES: Prestataire[] = [
    {
        id: '1',
        name: 'Elena Rodriguez',
        role: 'Maître Esthéticienne',
        image: 'https://images.pexels.com/photos/3762871/pexels-photo-3762871.jpeg?auto=compress&cs=tinysrgb&w=800',
        rating: 4.9,
        specialty: 'HydraFacial & Anti-Âge'
    },
    {
        id: '2',
        name: 'Sarah Chen',
        role: 'Massothérapeute Experte',
        image: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?auto=format&fit=crop&w=800&q=80',
        rating: 4.8,
        specialty: 'Tissus Profonds & Pierres Chaudes'
    },
    {
        id: '3',
        name: 'Sophie Laurent',
        role: 'Artist Ongulaire Luxe',
        image: 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=800&q=80',
        rating: 5.0,
        specialty: 'Manucure Russe & Nail Art'
    }
];

export const AMENITIES = [
    {
        name: 'Piscine à Débordement',
        image: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&q=80'
    },
    {
        name: 'Bar à Tisanes Bio',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&q=80'
    },
    {
        name: 'Suite de Méditation',
        image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80'
    }
];

export const USER_LOYALTY = {
    points: 1250,
    tier: 'Membre Gold',
    nextReward: 1500
};

export const SERVICE_HISTORY = [
    {
        id: 'h1',
        date: '2025-12-15',
        service: 'Signature Facial',
        prestataireId: '1',
        points: 50,
    }
];

export const RECOMMENDATIONS = [
    { id: '2', reason: 'Idéal pour votre récupération après le sport' },
    { id: '3', reason: 'Nouveau design saisonnier disponible' }
];
